spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geo_db
    username: postgres
    password: postgres

  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

grpc:
  server:
    port: 6565
