server:
  port: 8081

geo-db-api:
  headers:
    api-key:
      name: X-RapidAPI-Key
      value: 9004b3371cmsh30b93dd2060df4bp1f5787jsn0d7893c64d19
    api-host:
      name: X-RapidAPI-Host
      value: wft-geo-db.p.rapidapi.com
